name: Java CI

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3
      - name: Build project
        run: |
              cd ./workspace/fabbrica
              mvn -B compile --file pom.xml
  test:
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v3
        - name: Test project
          run: |
                cd ./workspace/fabbrica
                mvn test 

